# https://github.com/actions/go-dependency-submission
name: dependency-submission
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/go-dependency-submission@v1
        with:
          go-mod-path: go.mod
          go-build-target: main.go
